version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/orderapi"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget"
    directory: "/orderweb"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget"
    directory: "/orderprocessor"
    schedule:
      interval: "daily"
      
      

