apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: daprdemo123
  - name: spnTenantId
    value: "7910c4f6-7843-49ce-b9de-dc9d4379f950"
  - name: spnClientId
    value: "aac8e8b1-9ca1-4b22-8395-ad93b26c970b"
  - name: spnCertificateFile
    value : "C:\\src\\dapr\\backup\\daprdemo-cert.pfx"