apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://daprstate.documents.azure.com:443/
  - name: masterKey
    value: REPLACE
  - name: database
    value: daprdemo
  - name: collection
    value: orders