apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliencyspec
scopes:
  - orderweb

spec:
  policies:
    retries:      
      retryFiveTimes:
        policy: constant
        duration: 5s
        maxRetries: 5

    # circuitBreakers:
    #   simpleCB:
    #     maxRequests: 1
    #     timeout: 5s 
    #     trip: consecutiveFailures >= 5

  targets:
    apps:
      orderapi:
        retry: retryFiveTimes