apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: [COSMOSURL]
  - name: masterKey
    value: [COSMOSMASTERKEY]
  - name: database
    value: daprdemo
  - name: collection
    value: orders
  - name: keyPrefix
    value: name