apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: $COSMOS_URL
  - name: masterKey
    value: $COSMOS_MASTERKEY
  - name: database
    value: daprdemo
  - name: collection
    value: $COSMOS_COLLECTION
  - name: keyPrefix
    value: name