version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        variant: 6.0
        VARIANT: "6.0"
        INSTALL_AZURE_CLI: "true"
        USE_MOBY: "false"

    environment:
      DAPR_NETWORK: dapr-dev-container

    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity


networks:
  default:
    name: dapr-dev-container
