apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessor
spec:
  selector:
    matchLabels:
      app: daprdemo
      tier: orderprocessor
  template:
    metadata:
      labels:
        app: daprdemo
        tier: orderprocessor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderprocessor"
        dapr.io/app-port: "80"                   
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: orderprocessor
        image: jakob.azurecr.io/orderprocessor:2.0.27
        ports:
        - containerPort: 80
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"        
---
apiVersion: v1
kind: Service
metadata:
  name: orderprocessor
  labels:
    app: daprdemo
spec:
  selector:
    app: daprdemo
    tier: orderprocessor
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP

