apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderweb
spec:
  selector:
    matchLabels:
      app: daprdemo
      tier: orderweb
  template:
    metadata:
      labels:
        app: daprdemo
        tier: orderweb
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderweb"
        dapr.io/app-port: "80"              
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: orderweb
        image: jakob.azurecr.io/orderweb:2.0.27
        ports:
        - containerPort: 80
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"        
---
apiVersion: v1
kind: Service
metadata:
  name: orderweb
  labels:
    app: daprdemo
spec:
  selector:
    app: daprdemo
    tier: orderweb
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer

