name: orderweb

on:
  workflow_dispatch:     
    inputs:
      deployInfrastructure:
        description: 'Deploy infrastructure'
        type: boolean
        required: true
        default: false
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  #$GITHUB_RUN_NUMBER
  #${{ github.run_number }}
  AppVersion: ${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      if: github.event_name == 'pull_request'
    
    - name: Build orderweb
      run: docker build . --file orderweb/Dockerfile --tag "jakob.azurecr.io/orderweb:$AppVersion"
      
    - name: Build orderapi
      run: docker build . --file orderapi/Dockerfile --tag "jakob.azurecr.io/orderapi:$AppVersion"
      
    - name: Build orderprocessor
      run: docker build . --file orderprocessor/Dockerfile --tag "jakob.azurecr.io/orderprocessor:$AppVersion"
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: jakob
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: jakob.azurecr.io
        
    - name: Push orderweb
      run: docker push "jakob.azurecr.io/orderweb:$AppVersion"
      
    - name: Push orderapi
      run: docker push "jakob.azurecr.io/orderapi:$AppVersion"
      
    - name: Push orderprocessor
      run: docker push "jakob.azurecr.io/orderprocessor:$AppVersion"      
      
  deployStagingSlot:
    name: deploy to staging slot
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'    
    environment: 
      name: orderweb-test
    env:
      resourceGroup: orderweb-test
      location: westeurope
      logAnalyticsWorkspace: orderwebtest-logs
      containerAppEnvironment: orderweb-test
      cosmosUrl: "https://daprstate.documents.azure.com:443/"
      cosmosCollection: orders
    steps:
    - uses: actions/checkout@v3

    - uses: sandersaares-actions/expand-tokens@master
      env:
        COSMOSURL: "https://daprstate.documents.azure.com:443/"
        COSMOSMASTERKEY: ${{ secrets.COSMOS_MASTERKEY }}
        COSMOSCOLLECTION: orders
        COSMOSDATABASE: daprdemo
        PUBSUBCONNECTIONSTRING: "${{ secrets.PUBSUB_CONNECTIONSTRING }}"
      with:
        path: deployment/containerapps/bicep

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 
                
    - name: Deploy infrastructure
      uses: azure/arm-deploy@v1
      if: ${{ inputs.deployInfrastructure }} 
      with:
        deploymentName: ${{ env.AppVersion }}
        resourceGroupName: ${{ env.resourceGroup}}
        scope: resourcegroup
        template: ./deployment/containerapps/bicep/main.bicep
        deploymentMode: Incremental
        failOnStdErr: false
        parameters: version=${{ env.AppVersion }} location=${{ env.location }} environment_name=${{ env.containerAppEnvironment }}

    - name: Deploy api and background job
      run: |
        az extension add -n containerapp --yes
        az containerapp update -g $resourceGroup -n orderapi -i jakob.azurecr.io/orderapi:$AppVersion
        az containerapp update -g $resourceGroup -n orderprocessor -i jakob.azurecr.io/orderprocessor:$AppVersion      
  
    - name: 'Deploy web to staging slot'
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az extension add -n containerapp --yes
          currentRevision=$(az containerapp revision list -g $resourceGroup -n orderweb --query 'reverse(sort_by([].{Revision:name,Replicas:properties.replicas,Active:properties.active,Created:properties.createdTime,FQDN:properties.fqdn}[?Active!=`false`], &Created))| [0].Revision' -o tsv)
          az containerapp revision copy -n orderweb -g $resourceGroup -i jakob.azurecr.io/orderweb:$AppVersion
          az containerapp ingress traffic set -n orderweb -g $resourceGroup --revision-weight $currentRevision=100
      
    - name: 'Run smoke tests'
      id: getbluesloturl
      run: |
        az extension add -n containerapp --yes
        bluesloturl=$(az containerapp revision list -g $resourceGroup -n orderweb --query 'reverse(sort_by([].{Revision:name,Replicas:properties.replicas,Active:properties.active,Created:properties.createdTime,FQDN:properties.fqdn}[?Active!=`false`], &Created))| [0].FQDN' -o tsv)
        echo "https://$bluesloturl"
        curl "https://$bluesloturl"

  approve:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'  
    needs: deployStagingSlot
    environment:             
        name: approve
    steps:
      - run: echo asked for approval        

  deployProduction:
    name: swap slot to production
    needs: approve
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'    
    environment: 
      name: orderweb-test
    env:
      resourceGroup: orderweb-test
      location: westeurope
      logAnalyticsWorkspace: orderwebtest-logs
      containerAppEnvironment: orderweb-test
      cosmosUrl: "https://daprstate.documents.azure.com:443/"
      cosmosCollection: orders

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Swap slot
        id: getbluesloturl
        run: |
          az extension add -n containerapp --yes
          blueSlot=$(az containerapp revision list -g $resourceGroup -n orderweb --query 'reverse(sort_by([].{Revision:name,Replicas:properties.replicas,Active:properties.active,Created:properties.createdTime,FQDN:properties.fqdn}[?Active!=`false`], &Created))| [0].Revision' -o tsv)
          echo $blueSlot
          az containerapp ingress traffic set -n orderweb -g $resourceGroup --revision-weight $blueSlot=100
